name: game_template
description: A mobile game built in Flutter.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flame_audio: ^1.4.0
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.1.0
  go_router: ^6.0.4
  hooks_riverpod: ^2.0.0-dev.9
  logging: ^1.0.2
  shared_preferences: ^2.0.15

  # If you don't need one of the following dependencies,
  # delete the relevant line below, and get rid of any Dart code
  # that references the dependency.
  firebase_core: ^2.4.1  # Needed for Crashlytics below
  firebase_crashlytics: ^3.0.11  # Error reporting
  games_services: ^3.0.0  # Achievements and leaderboards
  google_mobile_ads: ^2.0.0  # Ads
  in_app_purchase: ^3.0.6  # In-app purchases

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  freezed: ^2.1.0+1
  test: ^1.21.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/music/
    - assets/audio/sfx/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon-adaptive-foreground.png"
